// PV ATCK DEF SPEED SPECIAL
export const pokemon = {
	dratini: {
		Name : "Dratini",
		InternalName: "DRATINI",
		Type1 : "DRAGON",
		BaseStats : [41,64,45,50,50,50],
		BaseEXP : 60,
		Pokedex : "A Dratini continually molts and sloughs off its old skin. It does so because the life energy within its body steadily builds to reach uncontrollable levels.",
		Moves: ["SCRATCH", "TAILWHIP"],
	},
	mimikyu: {
		Name: "Mimiqui",
		InternalName: "MIMIKYU",
		Type1: "FAIRY",
		BaseStats: [37, 56, 42, 90, 50, 50],
		BaseEXP: 112,
		Pokedex : "Mimiqui!",
		Moves: ["SCRATCH"],
	},
	growlithe: {
		Name : "Caninos",
		InternalName: "GROWLITHE",
		Type1 : "DRAGON",
		BaseStats : [41,60,45,50,50,50],
		BaseEXP : 60,
		Pokedex : "Il est courageux et fiable. Il se dresse vaillamment devant ses ennemis.",
		Moves: ["SCRATCH", "EMBER"],
	},
	pidgey : {
		Name : "Roucool",
		InternalName : "PIDGEY",
		Type1 : "NORMAL",
		Type2 : "FLYING",
		BaseStats : [40,45,40,56,35,35],
		BaseEXP : 50,
		Pokedex : "It has an extremely sharp sense of direction. It can unerringly return home to its nest, however far it may be removed from its familiar surroundings.",
		Moves: [ "TACKLE", "GROWL"], 
	},
	rattata : {
		Name : "Rattata",
		InternalName : "RATTATA",
		Type1 : "NORMAL",
		BaseStats : [30,56,35,72,25,35],
		BaseEXP : 51,
		Pokedex :" A Rattata is cautious in the extreme. Even while it is asleep, it constantly moves its ears and listens for danger. It will make its nest anywhere.",
		Moves: ["SCRATCH", "TAILWHIP"], 
	},
	caterpie: {
		Name : "Chenipan",
		InternalName : "CATERPIE",
		Type1 : "BUG",
		BaseStats : [45,30,35,45,20,20],
		BaseEXP : 39,
		Pokedex : "Its voracious appetite compels it to devour leaves bigger than itself without hesitation. It releases a terribly strong odor from its antennae.",
		Moves: ["TACKLE", "STRINGSHOT"], 
	},
	weedle: {
		Name : "Aspicot",
		InternalName : "WEEDLE",
		Type1 : "BUG", 
		Type2: "POISON",
		BaseStats : [40,35,30,50,20,20],
		BaseEXP : 39,
		Pokedex : "A Weedle has an extremely acute sense of smell. It distinguishes its favorite kinds of leaves from those it dislikes by sniffing with its big red proboscis (nose).",
		Moves: ["TACKLE", "STRINGSHOT"],
	},
	spearow: {
		Name : "Piafabec",
		InternalName : "SPEAROW",
		Type1 : "NORMAL",
		Type2: "FLYING",
		BaseStats : [40,60,30,70,31,31],
		BaseEXP : 52,
		Pokedex : "Its loud cry can be heard over half a mile away. If its high, keening cry is heard echoing all around, it is a sign that they are warning each other of danger.",
		Moves: ["PECK", "GROWL"], 
	},
    pikachu: {
		Name: "Pikachu",
		InternalName: "PIKACHU",
		Type1: "ELECTRIC",
		BaseStats: [35, 55, 40, 90, 50, 50],
		BaseEXP: 112,
		Pokedex : "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.",
		Moves: ["THUNDERSHOCK", "TAILWHIP", "GROWL"],
	},
    pikachad: {
		Name: "Pikachad",
		InternalName: "PIKACHAD",
		Type1: "ELECTRIC",
		BaseStats: [35, 55, 40, 90, 50, 50],
		BaseEXP: 112,
		Pokedex : "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.",
		Moves: ["THUNDERSHOCK", "TAILWHIP", "GROWL"],
	},
	nidoranfe: {
		Name : "Nidoran♀",
		InternalName: "NIDORANfE",
		Type1 : "POISON",
		BaseStats : [55,47,52,41,40,40],
		BaseEXP : 55,
		Pokedex : "Its highly toxic barbs are thought to have developed as protection for this small-bodied Pokémon. When enraged, it releases a horrible toxin from its horn.",
		Moves : [ "GROWL", "TACKLE"]
	},
	nidoranma: {
		Name : "Nidoran♂",
		InternalName: "NIDORANmA",
		Type1 : "POISON",
		BaseStats : [ 46,57,40,50,40,40],
		BaseEXP : 55,
		Pokedex : "Its highly toxic barbs are thought to have developed as protection for this small-bodied Pokémon. When enraged, it releases a horrible toxin from its horn.",
		Moves : ["TAILWHIP", "PECK"]
	},
    charmander: {
		Name: "Salamèche",
		InternalName: "CHARMANDER",
		Type1: "FIRE",
		BaseStats: [39, 52, 43, 65, 60, 50],
		BaseEXP: 62,
		Pokedex : "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is happy, and blazes when it is enraged.",
		Moves: ["SCRATCH", "EMBER", "GROWL"],
	},
	bulbasaur: {
		Name: "Bulbizarre",
		InternalName: "BULBASAUR",
		Type1: "GRASS",
		Type2: "POISON",
		BaseStats: [45, 49, 49, 45, 65, 65],
		BaseEXP: 64,
		Pokedex : "Bulbasaur can be seen napping in bright sunlight.",
		Moves: ["VINEWHIP"],
	},
    eevee: {
		Name: "Evoli",
		InternalName: "EEVEE",
		Type1: "NORMAL",
		BaseStats: [55, 55, 50, 55, 45, 65],
		BaseEXP: 65,
		Pokedex : "Ses multiples évolutions lui permettent de s'adapter à tout type de milieu.",
		Moves: ["TACKLE"],
	},
	kakuna: {
		Name : "Coconfort",
		InternalName: "KAKUNA",
		Type1 : "BUG",
		BaseStats : [45,25,50,35,25,25],
		BaseEXP : 72,
		Pokedex : "It remains virtually immobile while it clings to a tree. However, on the inside, it busily prepares for evolution. This is evident from how hot its shell becomes.",
		Moves: ["HARDEN"],
	},
	metapod:{
		Name : "Chrysacier",
		InternalName: "METAPOD",
		Type1 : "BUG",
		BaseStats : [50,20,55,30,25,25],
		BaseEXP : 72,
		Pokedex : "Its shell is as hard as an iron slab. A Metapod does not move very much because it is preparing its soft innards for evolution inside the shell.",
		Moves: ["HARDEN"],
	},
	beedrill :{
		Name : "Dardargnan",
		InternalName: "BEEDRILL",
		Type1 : "BUG",
		Type2 : "POISON",
		BaseStats : [65,90,40,75,45,80],
		BaseEXP : 198,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["FURYATTACK", "HARDEN"],
	},
	gastly :{
		Name : "Fantominus",
		InternalName: "GASTLY",
		Type1 : "GHOST",
		Type2 : "POISON",
		BaseStats : [30,56,35,72,25,35],
		BaseEXP : 69,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["LICK", "SPITE"],
	},
	haunter :{
		Name : "Spectrum",
		InternalName: "HAUNTER",
		Type1 : "GHOST",
		Type2 : "POISON",
		BaseStats : [30,56,35,72,25,35],
		BaseEXP : 69,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["LICK", "SPITE"],
	},
	meowth :{
		Name : "Miaouss",
		InternalName: "MEOWTH",
		Type1 : "NORMAL",
		BaseStats : [40,45,35,90,40,40],
		BaseEXP : 58,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["TACKLE", "SCRATCH"],
	},
	mankey :{
		Name : "Férosinge",
		InternalName: "MANKEY",
		Type1 : "COMBAT",
		BaseStats : [40,80,35,70,35,45],
		BaseEXP : 58,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["SCRATCH", "LEER", "KARATECHOP"],
	},
	machop :{
		Name : "Machoc",
		InternalName: "MACHOP",
		Type1 : "COMBAT",
		BaseStats : [70,80,50,35,35,35],
		BaseEXP : 61,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["TACKLE", "LEER", "KARATECHOP"],
	},
	geodude :{
		Name : "Racaillou",
		InternalName: "GEODUDE",
		Type1 : "ROCK",
		BaseStats : [40,80,100,20,30,30],
		BaseEXP : 60,
		Pokedex : "A Beedrill is extremely territorial. For safety reasons, no one should ever approach its nest. If angered, they will attack in a swarm.",
		Moves: ["HARDEN", "TACKLE"],
	},
	vaporeon :{
		Name : "Aquali",
		InternalName: "VAPOREON",
		Type1 : "WATER",
		BaseStats : [130,65,60,65,110,95],
		BaseEXP : 60,
		Pokedex : "Ce Pokémon peut contrôler l'eau à volonté. Wow.",
		Moves: ["TACKLE"],
	},
}